version: 2.1
workflows:
  build:
    jobs:
      - build-deploy:
          context: DEPLOY
jobs:
  build-deploy:

    working_directory: ~/na-tg-client

    docker:
      - image: circleci/openjdk:11.0.8

    steps: # a collection of executable commands

      - checkout # check out source code to working directory
      - setup_remote_docker

      - run: mvn -s .circleci/settings.xml clean package deploy # gets the project dependencies