version: 2.1
jobs:
  build:
    working_directory: ~/na-commons-communication

    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps: # a collection of executable commands

      - checkout # check out source code to working directory
      - add_ssh_keys
      - setup_remote_docker

      - restore_cache:
          keys:
            - na-commons-communication-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline # gets the project dependencies

      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: na-commons-communication-{{ checksum "pom.xml" }}

      - run: mvn clean package
